# Generated by Django 5.1.5 on 2025-03-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopy', '0003_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_name',
            new_name='name',
        ),
    ]
